# Generated by Django 4.2.2 on 2023-10-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=250)),
                ('two', models.CharField(max_length=250)),
                ('three', models.CharField(max_length=250)),
            ],
        ),
    ]
